apiVersion: v1
kind: Pod
metadata:
  name: host-thief
spec:
  containers:
  - name: bash
    image: bash
    volumeMounts:
    - mountPath: /host-root
      name: root-dir
  volumes:
  - name: root-dir
    hostPath:
      path: / # This is the "Attack" - trying to access the node's root
